const { useState } = React;

const aciklamalar = {
  girisBedeli: "Yatırımcıdan alınan hayvan başı giriş bedeli (KDV hariç)",
  girisKDV: "Yatırımcıdan alınan giriş bedeli üzerinden uygulanacak KDV oranı (%)",
  sutFiyati: "1 litre süt satış fiyatı (TL)",
  sutKDV: "Süt satışında uygulanan KDV oranı (%)",
  aylikSutMiktari: "Bir ineğin aylık verdiği ortalama süt miktarı (litre)",
  yillikBuzagiGeliri: "Bir ineğin yıllık doğurduğu buzağıdan elde edilen gelir (TL)",
  buzagiKDV: "Buzağı satışında uygulanan KDV oranı (%)",
  yemGideri: "Aylık hayvan başı yem maliyeti (TL)",
  veterinerGideriSirket: "Şirketin toplam veteriner gideri (aylık, TL)",
  veterinerGideriYatirimci: "Yatırımcıya ait hayvan için aylık veteriner gideri (TL)",
  kiraGideriSirket: "Şirketin aylık çiftlik kira gideri (TL)",
  cobanGideriYatirimci: "Yatırımcıya ait hayvan için aylık çoban gideri (TL)",
  cobanGideriSirket: "Şirketin toplam çoban gideri (aylık, TL)",
  yatirimciOdemeStopaj: "Yatırımcıya yapılan ödeme için uygulanacak stopaj oranı (%)",
  gelirVergisi: "Net kâr üzerinden alınan gelir vergisi oranı (%)",
  inekSayisiSirket: "Şirketin sahip olduğu toplam inek sayısı",
  inekSayisiBireysel: "Bireysel yatırımcıya ait inek sayısı",
  inekSayisiKurumsal: "Kurumsal yatırımcıya ait inek sayısı",
  amortismanGideriSirket: "Şirketin yıllık amortisman gideri (TL)",
  amortismanGideriYatirimci: "Yatırımcının yıllık amortisman gideri (hayvan başı, TL)",
  toplamKapasite: "Çiftliğin toplam hayvan kapasitesi",
  yatirimciTipi: "Yatırımcı tipi (kurumsal veya bireysel)"
};

const varsayilanVeri = {
  girisBedeli: 140000,
  girisKDV: 20,
  sutFiyati: 18,
  sutKDV: 1,
  aylikSutMiktari: 900,
  yillikBuzagiGeliri: 35000,
  buzagiKDV: 1,
  yemGideri: 2500,
  veterinerGideriSirket: 150000,
  veterinerGideriYatirimci: 0,
  kiraGideriSirket: 200000,
  cobanGideriYatirimci: 500,
  cobanGideriSirket: 100000,
  yatirimciOdemeStopaj: 20,
  gelirVergisi: 23,
  inekSayisiSirket: 300,
  inekSayisiBireysel: 1,
  inekSayisiKurumsal: 0,
  amortismanGideriSirket: 60000,
  amortismanGideriYatirimci: 2000,
  toplamKapasite: 300,
  yatirimciTipi: "bireysel"
};
